name: Deploy to GitHub Pages

on:
  push:
    branches:
      - testbuild2

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./_site
      - uses: actions/deploy-pages@v3
